"""Server-level harness config path resolution.

``harness/config.yaml`` is server-local infrastructure config (sandbox
provider, memory backend, checkpointer, ...). It is generated by
``setup.sh`` at first server startup and is gitignored; the committed
template is ``harness/config.example.yaml``.

When the local file is absent (fresh clone before setup), loaders fall
back to the template so the server still boots with sane defaults.
"""
from __future__ import annotations

from pathlib import Path

_HARNESS_DIR = Path(__file__).resolve().parent.parent

LOCAL_CONFIG = _HARNESS_DIR / "config.yaml"
EXAMPLE_CONFIG = _HARNESS_DIR / "config.example.yaml"


def server_config_path() -> Path:
    """Return the server config path, falling back to the example template."""
    if LOCAL_CONFIG.exists():
        return LOCAL_CONFIG
    return EXAMPLE_CONFIG
